<?php
/**
 * @file
 * Geocomplete module.
 */

/**
 *  Implements hook_ctools_plugin_directory().
 */
function geocomplete_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'search_api_location') {
    return 'plugins/' . $plugin_type;
  }
}

/**
 *  Implements hook_form_FORM_ID_alter().
 */
function geocomplete_form_views_exposed_form_alter(&$form, &$form_state, $form_id) {
  $flag = FALSE;
  foreach ($form_state['view']->filter as $filter_name => $filter_obj) {
    if ($filter_obj->options['plugin'] == 'geocomplete') {

      // Filter being used in this exposed form is the plugin we define in our module.
      $flag = TRUE;

      // Add specific class to each geocomplete input.
      $form[$filter_obj->field]['#attributes']['class'][] = 'geocomplete-input';

      // Add hidden fields for storing lat, lon, etc.
      $form[$filter_obj->field . '_geofield'] = array(
        '#type' => 'container',
        $filter_obj->field . '_lat' => array(
          '#type' => 'hidden',
          '#attributes' => array(
            'data-geocomplete-type' => 'lat',
          ),
        ),
        $filter_obj->field . '_lng' => array(
          '#type' => 'hidden',
          '#attributes' => array(
            'data-geocomplete-type' => 'lng',
          ),
        ),
        '#attributes' => array(
          'data-geocomplete-src' => $filter_obj->field,
        ),
      );

    }
  }

  if ($flag) {
    // Geocomplete field is used, add js.
    $form['#attached']['js'][] = array(
      'data' => 'http://maps.googleapis.com/maps/api/js?sensor=false&libraries=places',
      'type' => 'external'
    );
    $form['#attached']['js'][] = array(
      'data' => libraries_get_path('geocomplete') . '/jquery.geocomplete.js',
      'type' => 'file'
    );
    $form['#attached']['js'][] = array(
      'data' => drupal_get_path('module', 'geocomplete') . '/geocomplete.js',
      'type' => 'file'
    );
  }

}
